import type { SignalType } from '@/components/ui/signal-badge'

export const sampleTopSignal = {
  ticker: 'NVDA',
  companyName: 'NVIDIA Corporation',
  headline: 'CEO sold $12.4M',
  context: 'Largest sale since Q2 2023',
  value: 12400000,
  direction: 'sell' as const,
  insiderName: 'Jensen Huang',
  insiderTitle: 'CEO',
  timestamp: new Date('2024-01-08'),
  isCluster: false,
  isFirstInMonths: true,
  monthsSinceLast: 8,
  signals: [
    { type: 'c-suite' as SignalType },
    { type: 'unusual-size' as SignalType, label: '$10M+' },
  ],
}

export const sampleWatchlistItems = [
  {
    ticker: 'AAPL',
    companyName: 'Apple Inc.',
    insiderBuys30d: 3,
    insiderSells30d: 1,
    netFlow30d: 2500000,
    lastInsiderDate: new Date('2024-01-06'),
    lastInsiderName: 'Tim Cook',
    lastInsiderAction: 'bought',
    hasCluster: false,
    hasCongressTrade: true,
    has13FActivity: true,
  },
  {
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    insiderBuys30d: 0,
    insiderSells30d: 5,
    netFlow30d: -8200000,
    lastInsiderDate: new Date('2024-01-07'),
    lastInsiderName: 'Elon Musk',
    lastInsiderAction: 'sold',
    hasCluster: true,
    hasCongressTrade: false,
    has13FActivity: true,
  },
  {
    ticker: 'MSFT',
    companyName: 'Microsoft Corporation',
    insiderBuys30d: 2,
    insiderSells30d: 2,
    netFlow30d: 150000,
    lastInsiderDate: new Date('2024-01-05'),
    lastInsiderName: 'Satya Nadella',
    lastInsiderAction: 'bought',
    hasCluster: false,
    hasCongressTrade: false,
    has13FActivity: true,
  },
]

export const sampleActivityFeed = [
  {
    id: '1',
    type: 'insider' as const,
    ticker: 'AMZN',
    companyName: 'Amazon.com, Inc.',
    headline: 'CFO bought $2.1M',
    subtext: 'Brian Olsavsky',
    value: 2100000,
    direction: 'buy' as const,
    timestamp: new Date('2024-01-08'),
    signals: [
      { type: 'c-suite' as SignalType },
      { type: 'first-buy' as SignalType, label: 'First in 2y' },
    ],
  },
  {
    id: '2',
    type: 'insider' as const,
    ticker: 'XOM',
    companyName: 'Exxon Mobil Corporation',
    headline: '5 insiders bought $890K',
    subtext: 'Multiple executives',
    value: 890000,
    direction: 'buy' as const,
    timestamp: new Date('2024-01-07'),
    signals: [{ type: 'cluster' as SignalType, label: '5 insiders' }],
  },
  {
    id: '3',
    type: 'congress' as const,
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    headline: 'Nancy Pelosi Purchase',
    subtext: 'Rep. • $500K - $1M',
    value: 750000,
    direction: 'buy' as const,
    timestamp: new Date('2024-01-06'),
    signals: [{ type: 'congress' as SignalType }],
  },
  {
    id: '4',
    type: '13f' as const,
    ticker: 'META',
    companyName: 'Meta Platforms, Inc.',
    headline: 'Berkshire Hathaway holds $1.2B',
    subtext: '8.5M shares',
    value: 1200000000,
    direction: 'neutral' as const,
    timestamp: new Date('2024-01-05'),
    signals: [{ type: 'institutional' as SignalType }],
  },
  {
    id: '5',
    type: 'insider' as const,
    ticker: 'JPM',
    companyName: 'JPMorgan Chase & Co.',
    headline: 'Director sold $450K',
    subtext: 'James Dimon',
    value: 450000,
    direction: 'sell' as const,
    timestamp: new Date('2024-01-05'),
    signals: [],
  },
]

export const sampleCongressTrades = [
  {
    memberName: 'Nancy Pelosi',
    ticker: 'GOOGL',
    transactionType: 'Purchase',
    amountRange: '$500K - $1M',
    disclosureDate: '2024-01-06',
    chamber: 'house' as const,
  },
  {
    memberName: 'Dan Crenshaw',
    ticker: 'MSFT',
    transactionType: 'Purchase',
    amountRange: '$15K - $50K',
    disclosureDate: '2024-01-05',
    chamber: 'house' as const,
  },
  {
    memberName: 'Tommy Tuberville',
    ticker: 'AAPL',
    transactionType: 'Sale',
    amountRange: '$100K - $250K',
    disclosureDate: '2024-01-04',
    chamber: 'senate' as const,
  },
]

export const sample13FMovements = [
  {
    fundName: 'Berkshire Hathaway',
    ticker: 'AAPL',
    direction: 'increased' as const,
    sharesChange: 5000000,
    valueChange: 915000000,
  },
  {
    fundName: 'Citadel Advisors',
    ticker: 'NVDA',
    direction: 'new' as const,
    sharesChange: 2500000,
    valueChange: 1200000000,
  },
  {
    fundName: 'Renaissance Technologies',
    ticker: 'TSLA',
    direction: 'decreased' as const,
    sharesChange: -1800000,
    valueChange: -432000000,
  },
]

export const sampleTrendingTickers = [
  {
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    transactionCount: 12,
    uniqueInsiders: 5,
    totalBuyValue: 2500000,
    totalSellValue: 15000000,
    netFlow: -12500000,
    hasCluster: true,
    topInsiderName: 'Jensen Huang',
    topInsiderTitle: 'CEO',
  },
  {
    ticker: 'XOM',
    companyName: 'Exxon Mobil Corporation',
    transactionCount: 8,
    uniqueInsiders: 6,
    totalBuyValue: 4200000,
    totalSellValue: 0,
    netFlow: 4200000,
    hasCluster: true,
    topInsiderName: 'Darren Woods',
    topInsiderTitle: 'CEO',
  },
  {
    ticker: 'AMZN',
    companyName: 'Amazon.com, Inc.',
    transactionCount: 6,
    uniqueInsiders: 3,
    totalBuyValue: 3100000,
    totalSellValue: 500000,
    netFlow: 2600000,
    hasCluster: true,
    topInsiderName: 'Andy Jassy',
    topInsiderTitle: 'CEO',
  },
  {
    ticker: 'META',
    companyName: 'Meta Platforms, Inc.',
    transactionCount: 5,
    uniqueInsiders: 2,
    totalBuyValue: 0,
    totalSellValue: 8500000,
    netFlow: -8500000,
    hasCluster: false,
    topInsiderName: 'Mark Zuckerberg',
    topInsiderTitle: 'CEO',
  },
  {
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    transactionCount: 4,
    uniqueInsiders: 3,
    totalBuyValue: 1200000,
    totalSellValue: 2300000,
    netFlow: -1100000,
    hasCluster: true,
    topInsiderName: 'Sundar Pichai',
    topInsiderTitle: 'CEO',
  },
  {
    ticker: 'JPM',
    companyName: 'JPMorgan Chase & Co.',
    transactionCount: 3,
    uniqueInsiders: 2,
    totalBuyValue: 500000,
    totalSellValue: 450000,
    netFlow: 50000,
    hasCluster: false,
    topInsiderName: 'Jamie Dimon',
    topInsiderTitle: 'CEO',
  },
]
